repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==2.5.3
          - pydantic-settings==2.1.0
          - types-aiofiles==23.2.0.0
        args:
          - --config-file=pyproject.toml
          - --strict
        files: ^src/
        # Exclude legacy duplicate config module to avoid module-name collision
        exclude: ^src/config($|/)|^src/config\.py$
        pass_filenames: true
