version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: chimera-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infrastructure/observability/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - chimera_observability

  grafana:
    image: grafana/grafana:10.4.0
    container_name: chimera-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./infrastructure/observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infrastructure/observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - chimera_observability

  alertmanager:
    image: prom/alertmanager:latest
    container_name: chimera-alertmanager
    ports:
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - ./infrastructure/observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - chimera_observability

networks:
  chimera_observability:
    driver: bridge
