[tool.poetry]
name = "lolbot"
version = "0.1.0"
description = "Project Chimera - AI-powered League of Legends Discord Bot"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.2"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
cassiopeia = "^5.1.0"
asyncpg = "^0.29.0"
redis = "^5.0.1"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"
google-generativeai = "^0.3.2"
celery = "^5.3.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
mypy = "^1.8.0"
ruff = "^0.1.9"
pre-commit = "^3.6.0"
black = "^23.12.1"
isort = "^5.13.2"
types-aiofiles = "^23.2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "UP", "B", "SIM"]  # Removed "I" (isort rules) to use dedicated isort tool
ignore = ["E501"]  # Line too long
fixable = ["ALL"]
unfixable = []
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "cassiopeia",
    "cassiopeia.*",
    "discord",
    "discord.*",
    "asyncpg",
    "asyncpg.*",
    "aiohttp",
    "aiohttp.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
