"""
Data contracts for Project Chimera.
All models use Pydantic V2 with strict type checking.
"""

from .common import (
    BaseContract,
    Division,
    Platform,
    Position,
    Queue,
    Region,
    Tier,
)
from .events import (
    BaseEvent,
    BuildingKillEvent,
    BuildingType,
    ChampionKillEvent,
    ChampionSpecialKillEvent,
    ChampionTransformEvent,
    DragonSoulGivenEvent,
    EliteMonsterKillEvent,
    EventType,
    GameEndEvent,
    ItemDestroyedEvent,
    ItemEvent,
    ItemPurchasedEvent,
    ItemSoldEvent,
    ItemUndoEvent,
    KillType,
    LaneType,
    MonsterSubType,
    MonsterType,
    ObjectiveBountyEvent,
    PauseEvent,
    SkillLevelUpEvent,
    TimelineEvent,
    TowerType,
    TurretPlateDestroyedEvent,
    WardKillEvent,
    WardPlacedEvent,
    WardType,
)
from .match import (
    Ban,
    Challenges,
    Match,
    MatchInfo,
    MatchMetadata,
    Participant,
    Perks,
    Team,
)
from .summoner import (
    Account,
    ChallengeInfo,
    LeagueEntry,
    MasteryInfo,
    PlayerInfo,
    SummonerProfile,
)
from .timeline import (
    ChampionStats,
    DamageStats,
    Frame,
    MatchTimeline,
    ParticipantFrame,
    TimelineInfo,
    TimelineMetadata,
    TimelineParticipant,
)

__all__ = [
    # Common
    "BaseContract",
    "Division",
    "Platform",
    "Position",
    "Queue",
    "Region",
    "Tier",
    # Events
    "BaseEvent",
    "BuildingKillEvent",
    "BuildingType",
    "ChampionKillEvent",
    "ChampionSpecialKillEvent",
    "ChampionTransformEvent",
    "DragonSoulGivenEvent",
    "EliteMonsterKillEvent",
    "EventType",
    "GameEndEvent",
    "ItemDestroyedEvent",
    "ItemEvent",
    "ItemPurchasedEvent",
    "ItemSoldEvent",
    "ItemUndoEvent",
    "KillType",
    "LaneType",
    "MonsterSubType",
    "MonsterType",
    "ObjectiveBountyEvent",
    "PauseEvent",
    "SkillLevelUpEvent",
    "TimelineEvent",
    "TowerType",
    "TurretPlateDestroyedEvent",
    "WardKillEvent",
    "WardPlacedEvent",
    "WardType",
    # Match
    "Ban",
    "Challenges",
    "Match",
    "MatchInfo",
    "MatchMetadata",
    "Participant",
    "Perks",
    "Team",
    # Summoner
    "Account",
    "ChallengeInfo",
    "LeagueEntry",
    "MasteryInfo",
    "PlayerInfo",
    "SummonerProfile",
    # Timeline
    "ChampionStats",
    "DamageStats",
    "Frame",
    "MatchTimeline",
    "ParticipantFrame",
    "TimelineInfo",
    "TimelineMetadata",
    "TimelineParticipant",
]