name: Security & Secrets Audit

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  sast-lite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run secrets scanner
        run: |
          python scripts/audit_secrets.py
